### ISSUE TITLE
Style attribute of component passed as prop breaks

### ISSUE THREAD

**Issue by Dangoo** [sinnerschrader/patternplate-server#10]
@KnisterPeter:

When the style attribute is populated in a component which is passed as prop to another component the JSX transform breaks
 
````
<Page className="investment-app" stage={
    <StageTeaser>
        <Paragraph style={{ marginTop: 20 }}>
            Lorem Ipsum …
        </Paragraph>
    </StageTeaser>
}>
````

````
[patternplate-server] SyntaxError: unknown: Unexpected token (20:1)
  18 | 		
  19 | <Page className="investment-app" stage={
> 20 | 	return (
     |  ^
  21 | <StageTeaser image="/api/static/images/investment-detail/header.jpg">
  22 | 		<div className="dateline">Deutsche Bank auf dem Handy</div>
  23 | 		<h2 className="h2">Meine Bank App</h2>
    at Parser.pp.raise (/Users/dangoo/Projekte/DBA/pfb-patternplate/node_modules/patternplate/node_modules/babel-core/node_modules/babylon/lib/parser/location.js:24:13)
    at Parser.pp.unexpected (/Users/dangoo/Projekte/DBA/pfb-patternplate/node_modules/patternplate/node_modules/babel-core/node_modules/babylon/lib/parser/util.js:82:8)
    at Parser.pp.parseExprAtom (/Users/dangoo/Projekte/DBA/pfb-patternplate/node_modules/patternplate/node_modules/babel-core/node_modules/babylon/lib/parser/expression.js:425:12)
    at Parser.parseExprAtom (/Users/dangoo/Projekte/DBA/pfb-patternplate/node_modules/patternplate/node_modules/babel-core/node_modules/babylon/lib/plugins/jsx/index.js:412:22)
    at Parser.pp.parseExprSubscripts (/Users/dangoo/Projekte/DBA/pfb-patternplate/node_modules/patternplate/node_modules/babel-core/node_modules/babylon/lib/parser/expression.js:236:19)
````

**Comment by KnisterPeter** [comment]
To fix this we need to rework the react transform to use a parser instead of regexp to find the main jsx-expression.
This will need a bit of time.

**Comment by marionebl** [comment]
Will be adressed with https://github.com/sinnerschrader/patternplate-transform-react/commit/f7f7b995390104e9c7313131840b86c81544cbb9

**Comment by marionebl** [comment]
This issue was moved to sinnerschrader/patternplate#43
