### ISSUE TITLE
javascript execution fails in demo pattern

### ISSUE THREAD

**Issue by daf100** [sinnerschrader/patternplate-server#54]
javascript doesn't seem to work within demo.jsx. following snippet throws `Cannot convert undefined or null to object`. 
also 'console.log()'  throws a 'not defined' error.

```js
var icons = ["arrow-right", "plus", "minus"];
<ul className="demo-icons">
	{icons.map(function(icon) {
		return <li>
			<Pattern name={icon} size={48}></Pattern>
			<span className="icon-name">{icon}</span>
		</li>;
	})}
</ul>
```

**Comment by marionebl** [comment]
https://github.com/sinnerschrader/patternplate-transform-react-to-markup/issues/1

**Comment by marionebl** [comment]
@daf100 Could you provide the entire stack trace from the terminal console?

**Comment by daf100** [comment]
sure!

```bash
2016-02-23T11:14:36.366Z - silly: [patternplate-client] read cookie data {"theme":"light","themeTarget":"dark"}
2016-02-23T11:14:36.459Z - debug: [patternplate-server] [application:request] Tue Feb 23 2016 12:14:36 GMT+0100 (CET) - GET /api - 200 OK - 65ms
2016-02-23T11:14:36.503Z - debug: [patternplate-server] [application:request] Tue Feb 23 2016 12:14:36 GMT+0100 (CET) - GET /api/meta/ - 200 OK - 15ms
Warning: No route matches path "/pattern/atoms/icon". Make sure you have <Route path="/pattern/atoms/icon"> somewhere in your routes
2016-02-23T11:14:36.565Z - info: [patternplate-client] [application:request] No match for images/inline-icons.svg on /Users/daf/_dev/s2/erg-patternplate/static
2016-02-23T11:14:36.568Z - info: [patternplate-client] [application:request] Matched images/inline-icons.svg on /Users/daf/_dev/s2/erg-patternplate/node_modules/patternplate-client/static
2016-02-23T11:14:36.568Z - debug: [patternplate-client] [application:request] Tue Feb 23 2016 12:14:36 GMT+0100 (CET) - GET /static/images/inline-icons.svg - 200 OK - 9ms
2016-02-23T11:14:36.576Z - debug: [patternplate-client] [application:request] Tue Feb 23 2016 12:14:36 GMT+0100 (CET) - GET /pattern/atoms/icon - 200 OK - 213ms
2016-02-23T11:14:37.203Z - debug: [patternplate-client] [application:request] Tue Feb 23 2016 12:14:37 GMT+0100 (CET) - GET /script/index.bundle.js - 200 OK - 2ms
2016-02-23T11:14:39.059Z - debug: [patternplate-client] [application:request] Tue Feb 23 2016 12:14:37 GMT+0100 (CET) - GET /style/light.css - 200 OK - 1865ms
2016-02-23T11:14:39.515Z - info: [patternplate-client] [application:request] No match for images/icons.svg on /Users/daf/_dev/s2/erg-patternplate/static
2016-02-23T11:14:39.517Z - info: [patternplate-client] [application:request] Matched images/icons.svg on /Users/daf/_dev/s2/erg-patternplate/node_modules/patternplate-client/static
2016-02-23T11:14:39.518Z - debug: [patternplate-client] [application:request] Tue Feb 23 2016 12:14:39 GMT+0100 (CET) - GET /static/images/icons.svg - 200 OK - 11ms
2016-02-23T11:14:39.601Z - info: [patternplate-server] Initializing pattern "atoms/icon" with filters: [{"outFormats":[]}]
2016-02-23T11:14:39.613Z - info: [patternplate-server] Initialized pattern "atoms/icon" [12ms]
2016-02-23T11:14:39.687Z - info: [patternplate-server] Reading pattern "atoms/icon"
2016-02-23T11:14:39.723Z - info: [patternplate-server] Read pattern "atoms/icon" [36ms]
2016-02-23T11:14:39.723Z - info: [patternplate-server] Transforming pattern "atoms/icon"
2016-02-23T11:14:39.724Z - debug: [patternplate-server] Transforming "demo.jsx" of "atoms/icon" via "react"
2016-02-23T11:14:39.734Z - warn: [patternplate-server] [ ⚠  Deprecation ⚠ ] Implicit import "Pattern" for <Pattern/> detected in atoms/icon:demo.jsx. Implicit imports are deprecated and should be replaced with explicit ones. Implicit imports will be removed in version 1.0. Place "import Pattern from 'Pattern';" at the top of /Users/daf/_dev/s2/erg-patternplate/patterns/atoms/icon/demo.jsx.
2016-02-23T11:14:41.346Z - debug: [patternplate-server] Using the results of "react" for "demo.jsx" of "atoms/icon" as index
2016-02-23T11:14:41.347Z - debug: [patternplate-server] Transforming "demo.jsx" of "atoms/icon" via "react-to-markup"
Warning: Failed propType: Required prop `children` was not specified in `Icon`. Check the render method of `Icon`.
Warning: Each child in an array or iterator should have a unique "key" prop. Check the render method of `Icon`. See https://fb.me/react-warning-keys for more information.
2016-02-23T11:14:41.390Z - error: [patternplate-server] Error while transforming file "/Users/daf/_dev/s2/erg-patternplate/patterns/atoms/icon/demo.jsx" of pattern "atoms/icon" with transform "react-to-markup".
2016-02-23T11:14:41.390Z - error: [patternplate-server] Error in "atoms/icon" during transform "react-to-markup" of "/Users/daf/_dev/s2/erg-patternplate/patterns/atoms/icon/demo.jsx": Cannot convert undefined or null to object
2016-02-23T11:14:41.448Z - debug: [patternplate-server] TypeError: Cannot convert undefined or null to object
    at Function.from (native)
    at Object.babelHelpers.toConsumableArray (evalmachine.<anonymous>:161:18)
    at Icon.render (evalmachine.<anonymous>:460:127)
    at ReactCompositeComponentMixin._renderValidatedComponentWithoutOwnerOrContext (/Users/daf/_dev/s2/erg-patternplate/node_modules/react/lib/ReactCompositeComponent.js:587:34)
    at ReactCompositeComponentMixin._renderValidatedComponent (/Users/daf/_dev/s2/erg-patternplate/node_modules/react/lib/ReactCompositeComponent.js:607:32)
    at wrapper [as _renderValidatedComponent] (/Users/daf/_dev/s2/erg-patternplate/node_modules/react/lib/ReactPerf.js:66:21)
    at ReactCompositeComponentMixin.mountComponent (/Users/daf/_dev/s2/erg-patternplate/node_modules/react/lib/ReactCompositeComponent.js:220:30)
    at wrapper [as mountComponent] (/Users/daf/_dev/s2/erg-patternplate/node_modules/react/lib/ReactPerf.js:66:21)
    at Object.ReactReconciler.mountComponent (/Users/daf/_dev/s2/erg-patternplate/node_modules/react/lib/ReactReconciler.js:37:35)
    at ReactDOMComponent.ReactMultiChild.Mixin.mountChildren (/Users/daf/_dev/s2/erg-patternplate/node_modules/react/lib/ReactMultiChild.js:241:44)
2016-02-23T11:14:41.728Z - info: [patternplate-client] [application:request] No match for images/favicon-16.png on /Users/daf/_dev/s2/erg-patternplate/static
2016-02-23T11:14:41.730Z - info: [patternplate-client] [application:request] Matched images/favicon-16.png on /Users/daf/_dev/s2/erg-patternplate/node_modules/patternplate-client/static
2016-02-23T11:14:41.730Z - debug: [patternplate-client] [application:request] Tue Feb 23 2016 ```

**Comment by marionebl** [comment]
After some investigation the error was found in a spread on an undefined value, thus the error message is correct albeit cryptic. I'll extend the error logging of patternplate-transform-react-to-markup to print a bit more informative error output and add console.log again to the runtime executing the jsx templates

**Comment by marionebl** [comment]
I just released `patternplate-transform-react-to-markup@v0.2.9` which should give you better error messages in most cases.
